services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    user: root
    ports:
      - "9092:9092"   # host â†’ container
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Listeners: CONTROLLER internal, HOST for laptop, DOCKER for inside container
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Single-node shortcuts (prevents replication errors)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Logging
      KAFKA_LOG_DIRS: /kafka-logs
      
    volumes:
      - ./kafka_data:/kafka-logs


  mongodb:
    image: mongo:latest
    container_name: mongodb
    user: root   # <--- ADD THIS
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    command: ["mongod", "--bind_ip_all"]
    
volumes:
  kafka_data:
  mongodb_data: